/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Scanner;
import model.AppModel;

/**
 *
 * @author Acer
 */
public class AppViewFrame extends javax.swing.JFrame {
    private final java.awt.Color loginNormalBg  = new java.awt.Color(0, 0, 0);
    private final java.awt.Color loginNormalFg  = new java.awt.Color(239, 196, 4);
    private final java.awt.Color loginHoverBg   = new java.awt.Color(239, 196, 4);  // yellow
    private final java.awt.Color loginHoverFg   = java.awt.Color.BLACK; 
    private final Color viewNormalBg = Color.BLACK; // F1C40F
    private final Color viewNormalFg = new Color(0xF1, 0xC4, 0x0F);
    private final Color viewHoverBg  = new Color(0xF1, 0xC4, 0x0F);
    private final Color viewHoverFg  = Color.BLACK;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppViewFrame.class.getName());
    private final AppModel model = new AppModel();

    /**
     * Creates new form AppViewFrame
     */
    public AppViewFrame() {
        initComponents();
            setupHomeCardLayouts();
            loadHomeCards();
            logoutButton.setFocusPainted(false);
            logoutButton.setContentAreaFilled(true);
            logoutButton.setBorderPainted(false);

            logoutButton.setBorder(
                new javax.swing.border.LineBorder(
                    new java.awt.Color(0, 0, 0), // border color (black)
                    2,                            // thickness
                    true                          // rounded corners
                )
            );
    }
    
    private void setupHomeCardLayouts() {
        recentlyAddedPanel.setLayout(new java.awt.GridLayout(1, 3, 60, 0));
        recentlyAddedPanel.setBackground(java.awt.Color.WHITE);
    }
    
    private void loadHomeCards() {
        recentlyAddedPanel.removeAll();
        browseCardsPanel.removeAll(); 
        browseCardsPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));
        browseCardsPanel.setBorder(
            javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        );
        
        java.util.List<AppModel.RecipeData> recent = model.getRecentlyAdded(4);
        for (AppModel.RecipeData r : recent) {
            recentlyAddedPanel.add(createRecipeCard(r));
        }
        java.util.List<AppModel.RecipeData> allRecipes = model.getAllRecipes();
        for (AppModel.RecipeData r : allRecipes) {
            browseCardsPanel.add(createRecipeCard(r));
        }

        recentlyAddedPanel.revalidate();
        recentlyAddedPanel.repaint();
        browseCardsPanel.revalidate();
        browseCardsPanel.repaint();
    }

    private void handleLogin() {
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());

        CardLayout cl = (CardLayout) getContentPane().getLayout();

        if (username.isEmpty() && password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter username and password.","Validation Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (username.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter your username.","Validation Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter your password.","Validation Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (username.equals("admin") && password.equals("12345")) {
            // admin
            cl.show(getContentPane(), "card4");   
        } else if (username.equals("user") && password.equals("67890")) {
            // user
            cl.show(getContentPane(), "card2");   
            loadHomeCards();  
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,"User not found!","Login Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void setupHistoryLayout() {
        browseHistoryPanel.setLayout(new java.awt.GridLayout(0, 4, 20, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        subTitleLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        loginPageImage = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        navMainPanel = new javax.swing.JPanel();
        navigationPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        myHistoryButton = new javax.swing.JButton();
        browseRecipeButton = new javax.swing.JButton();
        myRecipeRequestButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        basePanel = new javax.swing.JPanel();
        homePanelUser = new javax.swing.JPanel();
        myStatsLabel = new javax.swing.JLabel();
        recentlyAddedPanel = new javax.swing.JPanel();
        totalRecipes = new javax.swing.JLabel();
        totalRecipesNumber = new javax.swing.JLabel();
        recipesCookedNumber = new javax.swing.JLabel();
        requestedNumber = new javax.swing.JLabel();
        bannerPanel = new javax.swing.JPanel();
        bannerHomePage = new javax.swing.JLabel();
        requestedLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        requestedNumber1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        yetToCookNumber = new javax.swing.JLabel();
        yetToCook = new javax.swing.JLabel();
        totalRecipesLogo = new javax.swing.JLabel();
        recipesCookedLogo = new javax.swing.JLabel();
        requestedLogo = new javax.swing.JLabel();
        yetToCookLogo = new javax.swing.JLabel();
        myStatsLabel1 = new javax.swing.JLabel();
        browseRecipesPanel = new javax.swing.JPanel();
        browsePanel = new javax.swing.JPanel();
        browseTopPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        browseScrollPane = new javax.swing.JScrollPane();
        browseCardsPanel = new javax.swing.JPanel();
        myHistoryPanel = new javax.swing.JPanel();
        historyPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        historyScrollPane = new java.awt.ScrollPane();
        browseHistoryPanel = new javax.swing.JPanel();
        recipeRequestPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(248, 237, 236));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        subTitleLabel.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        subTitleLabel.setText("Let's get started!");

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        titleLabel.setText("Welcome to Cookipedia");

        usernameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(239, 196, 4));
        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel)
                            .addComponent(titleLabel)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(subTitleLabel)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTitleLabel)
                .addGap(96, 96, 96)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(239, 196, 4));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        loginPageImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginpage.png"))); // NOI18N
        jPanel8.add(loginPageImage, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(loginPanel, "card3");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );

        getContentPane().add(adminPanel, "card4");

        userPanel.setBackground(new java.awt.Color(255, 255, 255));

        navMainPanel.setBackground(new java.awt.Color(244, 196, 4));
        navMainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        navMainPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        navMainPanel.setLayout(null);

        navigationPanel.setBackground(new java.awt.Color(96, 26, 26));

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        navMainPanel.add(navigationPanel);
        navigationPanel.setBounds(0, 130, 190, 550);

        homeButton.setBackground(new java.awt.Color(96, 26, 26));
        homeButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(null);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        homeButton.setFocusPainted(false);
        homeButton.setRequestFocusEnabled(false);
        homeButton.setRolloverEnabled(false);
        homeButton.setVerifyInputWhenFocusTarget(false);
        homeButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeButtonFocusGained(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        navMainPanel.add(homeButton);
        homeButton.setBounds(300, 0, 120, 60);

        myHistoryButton.setBackground(new java.awt.Color(96, 26, 26));
        myHistoryButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myHistoryButton.setText("History");
        myHistoryButton.setBorder(null);
        myHistoryButton.setBorderPainted(false);
        myHistoryButton.setContentAreaFilled(false);
        myHistoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myHistoryButton.setFocusPainted(false);
        myHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myHistoryButtonActionPerformed(evt);
            }
        });
        navMainPanel.add(myHistoryButton);
        myHistoryButton.setBounds(580, 0, 120, 60);

        browseRecipeButton.setBackground(new java.awt.Color(96, 26, 26));
        browseRecipeButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        browseRecipeButton.setText("Recipes");
        browseRecipeButton.setBorder(null);
        browseRecipeButton.setBorderPainted(false);
        browseRecipeButton.setContentAreaFilled(false);
        browseRecipeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        browseRecipeButton.setDefaultCapable(false);
        browseRecipeButton.setFocusPainted(false);
        browseRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseRecipeButtonActionPerformed(evt);
            }
        });
        navMainPanel.add(browseRecipeButton);
        browseRecipeButton.setBounds(440, 0, 120, 60);

        myRecipeRequestButton.setBackground(new java.awt.Color(96, 26, 26));
        myRecipeRequestButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myRecipeRequestButton.setText("Recipe Request");
        myRecipeRequestButton.setBorder(null);
        myRecipeRequestButton.setBorderPainted(false);
        myRecipeRequestButton.setContentAreaFilled(false);
        myRecipeRequestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myRecipeRequestButton.setFocusPainted(false);
        navMainPanel.add(myRecipeRequestButton);
        myRecipeRequestButton.setBounds(720, 0, 140, 60);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        navMainPanel.add(jSeparator1);
        jSeparator1.setBounds(710, 20, 10, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        navMainPanel.add(jSeparator2);
        jSeparator2.setBounds(430, 20, 10, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        navMainPanel.add(jSeparator3);
        jSeparator3.setBounds(570, 20, 10, 30);

        logoutButton.setBackground(new java.awt.Color(0, 0, 0));
        logoutButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 204, 0));
        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        navMainPanel.add(logoutButton);
        logoutButton.setBounds(1110, 10, 100, 42);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        navMainPanel.add(logo);
        logo.setBounds(20, 0, 60, 58);

        basePanel.setBackground(new java.awt.Color(255, 255, 255));
        basePanel.setLayout(new java.awt.CardLayout());

        homePanelUser.setBackground(new java.awt.Color(255, 255, 255));

        myStatsLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myStatsLabel.setText("Recently Added");

        recentlyAddedPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        totalRecipes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalRecipes.setText("Total Recipes");

        totalRecipesNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalRecipesNumber.setText("0");

        recipesCookedNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        recipesCookedNumber.setText("Recipes Cooked");

        requestedNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        requestedNumber.setText("0");

        bannerPanel.setBackground(new java.awt.Color(0, 0, 0));

        bannerHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner.png"))); // NOI18N

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bannerHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bannerHomePage))
        );

        requestedLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        requestedLabel1.setText("Requested");

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        requestedNumber1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        requestedNumber1.setText("0");

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        yetToCookNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        yetToCookNumber.setText("0");

        yetToCook.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        yetToCook.setText("Yet to Cook");

        totalRecipesLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol1.png"))); // NOI18N

        recipesCookedLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol2.png"))); // NOI18N

        requestedLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol3.png"))); // NOI18N

        yetToCookLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol4.png"))); // NOI18N

        myStatsLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myStatsLabel1.setText("Stats");

        javax.swing.GroupLayout homePanelUserLayout = new javax.swing.GroupLayout(homePanelUser);
        homePanelUser.setLayout(homePanelUserLayout);
        homePanelUserLayout.setHorizontalGroup(
            homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bannerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homePanelUserLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelUserLayout.createSequentialGroup()
                        .addComponent(myStatsLabel)
                        .addContainerGap())
                    .addGroup(homePanelUserLayout.createSequentialGroup()
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(totalRecipes))
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(totalRecipesNumber))
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(totalRecipesLogo)))
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(recipesCookedNumber))
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(requestedNumber1))
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(recipesCookedLogo)))
                        .addGap(84, 84, 84)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homePanelUserLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(yetToCook))
                                    .addGroup(homePanelUserLayout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(yetToCookNumber)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yetToCookLogo)
                                .addGap(121, 121, 121)))
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                                        .addComponent(requestedNumber)
                                        .addGap(180, 180, 180))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                                        .addComponent(requestedLabel1)
                                        .addGap(147, 147, 147))))
                            .addGroup(homePanelUserLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(requestedLogo))))
                    .addGroup(homePanelUserLayout.createSequentialGroup()
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myStatsLabel1)
                            .addComponent(recentlyAddedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        homePanelUserLayout.setVerticalGroup(
            homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelUserLayout.createSequentialGroup()
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(myStatsLabel1)
                .addGap(18, 18, 18)
                .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(recipesCookedLogo)
                            .addComponent(yetToCookLogo)
                            .addComponent(totalRecipesLogo)
                            .addComponent(requestedLogo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recipesCookedNumber)
                            .addComponent(yetToCook, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requestedLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalRecipesNumber)
                            .addComponent(requestedNumber1)
                            .addComponent(yetToCookNumber)
                            .addComponent(requestedNumber))))
                .addGap(53, 53, 53)
                .addComponent(myStatsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recentlyAddedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );

        basePanel.add(homePanelUser, "card6");

        browseRecipesPanel.setBackground(new java.awt.Color(255, 255, 255));

        browsePanel.setBackground(new java.awt.Color(255, 255, 255));

        browseTopPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Search any recipe");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Sort By:");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Name");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 0));
        jButton3.setText("Difficulty");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout browseTopPanelLayout = new javax.swing.GroupLayout(browseTopPanel);
        browseTopPanel.setLayout(browseTopPanelLayout);
        browseTopPanelLayout.setHorizontalGroup(
            browseTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseTopPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        browseTopPanelLayout.setVerticalGroup(
            browseTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseTopPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(browseTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browseTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jButton1)
                        .addComponent(jButton3))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        browseScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        browseScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        browseCardsPanel.setBackground(new java.awt.Color(255, 255, 255));
        browseCardsPanel.setAutoscrolls(true);
        browseCardsPanel.setLayout(new java.awt.GridLayout(1, 0));
        browseScrollPane.setViewportView(browseCardsPanel);

        javax.swing.GroupLayout browsePanelLayout = new javax.swing.GroupLayout(browsePanel);
        browsePanel.setLayout(browsePanelLayout);
        browsePanelLayout.setHorizontalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browseTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(browsePanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(browseScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        browsePanelLayout.setVerticalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browsePanelLayout.createSequentialGroup()
                .addComponent(browseTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(browseScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout browseRecipesPanelLayout = new javax.swing.GroupLayout(browseRecipesPanel);
        browseRecipesPanel.setLayout(browseRecipesPanelLayout);
        browseRecipesPanelLayout.setHorizontalGroup(
            browseRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        browseRecipesPanelLayout.setVerticalGroup(
            browseRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(browsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        basePanel.add(browseRecipesPanel, "card4");

        myHistoryPanel.setBackground(new java.awt.Color(255, 255, 255));

        historyPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Search recipe in your history");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Sort By:");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 0));
        jButton2.setText("Name");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 204, 0));
        jButton4.setText("Difficulty");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jButton2)
                        .addComponent(jButton4))
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        browseHistoryPanel.setLayout(new java.awt.GridLayout());
        historyScrollPane.add(browseHistoryPanel);

        javax.swing.GroupLayout myHistoryPanelLayout = new javax.swing.GroupLayout(myHistoryPanel);
        myHistoryPanel.setLayout(myHistoryPanelLayout);
        myHistoryPanelLayout.setHorizontalGroup(
            myHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(myHistoryPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(historyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myHistoryPanelLayout.setVerticalGroup(
            myHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myHistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(historyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        basePanel.add(myHistoryPanel, "card3");

        recipeRequestPanel.setBackground(new java.awt.Color(204, 51, 255));

        javax.swing.GroupLayout recipeRequestPanelLayout = new javax.swing.GroupLayout(recipeRequestPanel);
        recipeRequestPanel.setLayout(recipeRequestPanelLayout);
        recipeRequestPanelLayout.setHorizontalGroup(
            recipeRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
        );
        recipeRequestPanelLayout.setVerticalGroup(
            recipeRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );

        basePanel.add(recipeRequestPanel, "card2");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(basePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addComponent(navMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(userPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JPanel createRecipeCard(AppModel.RecipeData r) {
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setPreferredSize(new java.awt.Dimension(220, 260));
        card.setBackground(java.awt.Color.WHITE);
        card.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(230, 230, 230), 1, true));
        card.setLayout(new java.awt.BorderLayout(0, 0)); // No gaps!

        // Image at top - full width, no margins
        javax.swing.JLabel imgLabel = new javax.swing.JLabel();
        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setOpaque(true);
        imgLabel.setBackground(new Color(245, 245, 245));

        if (r.imagePath != null) {
            java.net.URL imgUrl = getClass().getResource(r.imagePath);
            if (imgUrl != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                java.awt.Image scaled = icon.getImage().getScaledInstance(
                    218, 150, java.awt.Image.SCALE_SMOOTH);
                imgLabel.setIcon(new javax.swing.ImageIcon(scaled));
            } else {
                imgLabel.setText("No image");
            }
        } else {
            imgLabel.setText("No image");
        }

        // Text center with larger font
        javax.swing.JLabel lblTitle = new javax.swing.JLabel(r.title);
        lblTitle.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 15));

        javax.swing.JLabel lblInfo = new javax.swing.JLabel(
            r.cuisine + " • " + r.difficulty + " • " + r.prepTime + " min" + " • " + r.rating + " ★");
        lblInfo.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 12)); 
        lblInfo.setForeground(new java.awt.Color(120, 120, 120));

        javax.swing.JPanel center = new javax.swing.JPanel();
        center.setBackground(java.awt.Color.WHITE);
        center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.Y_AXIS));
        center.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 10)); // Reduced side padding
        center.add(lblTitle);
        center.add(javax.swing.Box.createVerticalStrut(3));
        center.add(lblInfo);

        // Button at bottom - CENTERED
        javax.swing.JButton btnView = new javax.swing.JButton("View");
        btnView.setBackground(viewNormalBg);
        btnView.setForeground(viewNormalFg);
        btnView.setFocusPainted(false);
        btnView.setBorderPainted(false);
        btnView.setContentAreaFilled(true);
        btnView.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        btnView.setFocusPainted(false);
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.setPreferredSize(new java.awt.Dimension(80, 30));
        
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                btnView.setBackground(viewHoverBg);
                btnView.setForeground(viewHoverFg);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                btnView.setBackground(viewNormalBg);
                btnView.setForeground(viewNormalFg);
            }
        });


        javax.swing.JPanel bottom = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));
        bottom.setBackground(java.awt.Color.WHITE);
        bottom.add(btnView);

        // Add all components to card
        card.add(imgLabel, java.awt.BorderLayout.NORTH);
        card.add(center, java.awt.BorderLayout.CENTER);
        card.add(bottom, java.awt.BorderLayout.SOUTH);

        return card;
    }

    
    
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        handleLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setBackground(loginHoverBg);
        loginButton.setForeground(loginHoverFg);
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setBackground(loginNormalBg);
        loginButton.setForeground(loginNormalFg);
    }//GEN-LAST:event_loginButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure you want to log out?","Confirm Logout",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            CardLayout cl = (CardLayout) getContentPane().getLayout();
            cl.show(getContentPane(), "card3");
            usernameField.setText("");
            passwordField.setText("");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void myHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myHistoryButtonActionPerformed
        CardLayout cl = (CardLayout) basePanel.getLayout();
        cl.show(basePanel, "card3");
    }//GEN-LAST:event_myHistoryButtonActionPerformed

    private void browseRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseRecipeButtonActionPerformed
        CardLayout cl = (CardLayout) basePanel.getLayout();
        cl.show(basePanel, "card4");   // browseRecipesPanel
        loadHomeCards();
    }//GEN-LAST:event_browseRecipeButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        CardLayout cl = (CardLayout) basePanel.getLayout();
        cl.show(basePanel, "card6");   // homePanelUser
        loadHomeCards();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void homeButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeButtonFocusGained
        CardLayout cl = (CardLayout) basePanel.getLayout();
        cl.show(basePanel, "card2");
    }//GEN-LAST:event_homeButtonFocusGained

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setBackground(loginHoverBg);
        logoutButton.setForeground(loginHoverFg);
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setBackground(loginNormalBg);
        logoutButton.setForeground(loginNormalFg);
    }//GEN-LAST:event_logoutButtonMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppViewFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel bannerHomePage;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JPanel basePanel;
    private javax.swing.JPanel browseCardsPanel;
    private javax.swing.JPanel browseHistoryPanel;
    private javax.swing.JPanel browsePanel;
    private javax.swing.JButton browseRecipeButton;
    private javax.swing.JPanel browseRecipesPanel;
    private javax.swing.JScrollPane browseScrollPane;
    private javax.swing.JPanel browseTopPanel;
    private javax.swing.JPanel historyPanel;
    private java.awt.ScrollPane historyScrollPane;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanelUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginPageImage;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myHistoryButton;
    private javax.swing.JPanel myHistoryPanel;
    private javax.swing.JButton myRecipeRequestButton;
    private javax.swing.JLabel myStatsLabel;
    private javax.swing.JLabel myStatsLabel1;
    private javax.swing.JPanel navMainPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel recentlyAddedPanel;
    private javax.swing.JPanel recipeRequestPanel;
    private javax.swing.JLabel recipesCookedLogo;
    private javax.swing.JLabel recipesCookedNumber;
    private javax.swing.JLabel requestedLabel1;
    private javax.swing.JLabel requestedLogo;
    private javax.swing.JLabel requestedNumber;
    private javax.swing.JLabel requestedNumber1;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalRecipes;
    private javax.swing.JLabel totalRecipesLogo;
    private javax.swing.JLabel totalRecipesNumber;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel yetToCook;
    private javax.swing.JLabel yetToCookLogo;
    private javax.swing.JLabel yetToCookNumber;
    // End of variables declaration//GEN-END:variables
}
