/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.Scanner;
import model.AppModel;

/**
 *
 * @author Acer
 */
public class AppViewFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppViewFrame.class.getName());
    private final AppModel model = new AppModel();

    /**
     * Creates new form AppViewFrame
     */
    public AppViewFrame() {
        initComponents();
            setupHomeCardLayouts();
            loadHomeCards();
    }
    
    private void setupHomeCardLayouts() {
        recentlyAddedPanel.setLayout(new java.awt.GridLayout(1, 3, 60, 0));
    }
    
    private void loadHomeCards() {
        recentlyAddedPanel.removeAll();
        java.util.List<AppModel.RecipeData> recent = model.getRecentlyAdded(3);
        for (AppModel.RecipeData r : recent) {
            recentlyAddedPanel.add(createRecipeCard(r));
        }

        recentlyAddedPanel.revalidate();
        recentlyAddedPanel.repaint();
    }


    private void handleLogin() {
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());

        CardLayout cl = (CardLayout) getContentPane().getLayout();

        if (username.isEmpty() && password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter username and password.","Validation Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (username.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter your username.","Validation Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,"Please enter your password.","Validation Error",javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (username.equals("admin") && password.equals("12345")) {
            // admin
            cl.show(getContentPane(), "card4");   
        } else if (username.equals("user") && password.equals("67890")) {
            // user
            cl.show(getContentPane(), "card2");   
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,"User not found!","Login Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        subTitleLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        loginPageImg = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        navMainPanel = new javax.swing.JPanel();
        navigationPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        browseRecipeButton = new javax.swing.JButton();
        myFavoriteButton = new javax.swing.JButton();
        myHistoryButton = new javax.swing.JButton();
        myRecipeRequestButton = new javax.swing.JButton();
        topNavPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        basePanel = new javax.swing.JPanel();
        homePanelUser = new javax.swing.JPanel();
        myStatsLabel = new javax.swing.JLabel();
        myFavouritePanel = new javax.swing.JPanel();
        myFavourtiteLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        myFavouritesNumber = new javax.swing.JLabel();
        symbol1 = new javax.swing.JLabel();
        recipesCookedPanel = new javax.swing.JPanel();
        recipesCookedLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        recipesCookedNumber = new javax.swing.JLabel();
        symbol2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        requestedLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        requestedNumber = new javax.swing.JLabel();
        symbol3 = new javax.swing.JLabel();
        recentlyAddedPanel = new javax.swing.JPanel();
        myStatsLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        browseRecipesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(248, 237, 236));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        subTitleLabel.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        subTitleLabel.setText("Let's get started!");

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        titleLabel.setText("Welcome to Cookipedia");

        usernameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        loginButton.setBackground(new java.awt.Color(93, 23, 23));
        loginButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel)
                            .addComponent(titleLabel)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(subTitleLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTitleLabel)
                .addGap(59, 59, 59)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(248, 237, 236));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        loginPageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginpage.png"))); // NOI18N
        jPanel8.add(loginPageImg, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        getContentPane().add(loginPanel, "card3");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1202, Short.MAX_VALUE)
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(adminPanel, "card4");

        userPanel.setBackground(new java.awt.Color(255, 255, 255));

        navMainPanel.setBackground(new java.awt.Color(96, 26, 26));
        navMainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        navMainPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        navMainPanel.setLayout(null);

        navigationPanel.setBackground(new java.awt.Color(96, 26, 26));

        homeButton.setBackground(new java.awt.Color(96, 26, 26));
        homeButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        homeButton.setFocusPainted(false);
        homeButton.setRequestFocusEnabled(false);
        homeButton.setRolloverEnabled(false);
        homeButton.setVerifyInputWhenFocusTarget(false);
        homeButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeButtonFocusGained(evt);
            }
        });

        browseRecipeButton.setBackground(new java.awt.Color(96, 26, 26));
        browseRecipeButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        browseRecipeButton.setForeground(new java.awt.Color(255, 255, 255));
        browseRecipeButton.setText("Browse Recipes");
        browseRecipeButton.setBorder(null);
        browseRecipeButton.setBorderPainted(false);
        browseRecipeButton.setContentAreaFilled(false);
        browseRecipeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        browseRecipeButton.setDefaultCapable(false);
        browseRecipeButton.setFocusPainted(false);
        browseRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseRecipeButtonActionPerformed(evt);
            }
        });

        myFavoriteButton.setBackground(new java.awt.Color(96, 26, 26));
        myFavoriteButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myFavoriteButton.setForeground(new java.awt.Color(255, 255, 255));
        myFavoriteButton.setText("My Favorites");
        myFavoriteButton.setBorder(null);
        myFavoriteButton.setBorderPainted(false);
        myFavoriteButton.setContentAreaFilled(false);
        myFavoriteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myFavoriteButton.setFocusPainted(false);

        myHistoryButton.setBackground(new java.awt.Color(96, 26, 26));
        myHistoryButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        myHistoryButton.setText("My History");
        myHistoryButton.setBorder(null);
        myHistoryButton.setBorderPainted(false);
        myHistoryButton.setContentAreaFilled(false);
        myHistoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myHistoryButton.setFocusPainted(false);
        myHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myHistoryButtonActionPerformed(evt);
            }
        });

        myRecipeRequestButton.setBackground(new java.awt.Color(96, 26, 26));
        myRecipeRequestButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myRecipeRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        myRecipeRequestButton.setText("My Recipe Request");
        myRecipeRequestButton.setBorder(null);
        myRecipeRequestButton.setBorderPainted(false);
        myRecipeRequestButton.setContentAreaFilled(false);
        myRecipeRequestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myRecipeRequestButton.setFocusPainted(false);

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseRecipeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myFavoriteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myHistoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myRecipeRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseRecipeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myFavoriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myRecipeRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        navMainPanel.add(navigationPanel);
        navigationPanel.setBounds(0, 130, 190, 550);

        topNavPanel.setBackground(new java.awt.Color(96, 26, 26));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        logoutButton.setBackground(new java.awt.Color(96, 26, 26));
        logoutButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topNavPanelLayout = new javax.swing.GroupLayout(topNavPanel);
        topNavPanel.setLayout(topNavPanelLayout);
        topNavPanelLayout.setHorizontalGroup(
            topNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topNavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        topNavPanelLayout.setVerticalGroup(
            topNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topNavPanelLayout.createSequentialGroup()
                .addGroup(topNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topNavPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo))
                    .addGroup(topNavPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logoutButton)))
                .addGap(8, 8, 8))
        );

        navMainPanel.add(topNavPanel);
        topNavPanel.setBounds(0, 0, 210, 70);

        basePanel.setBackground(new java.awt.Color(255, 255, 255));
        basePanel.setLayout(new java.awt.CardLayout());

        homePanelUser.setBackground(new java.awt.Color(255, 255, 255));

        myStatsLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myStatsLabel.setForeground(new java.awt.Color(120, 1, 1));
        myStatsLabel.setText("Recently Added");

        myFavouritePanel.setBackground(new java.awt.Color(254, 238, 238));

        myFavourtiteLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myFavourtiteLabel.setText("My Favourites");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("|");

        myFavouritesNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myFavouritesNumber.setText("0");

        symbol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol1.png"))); // NOI18N

        javax.swing.GroupLayout myFavouritePanelLayout = new javax.swing.GroupLayout(myFavouritePanel);
        myFavouritePanel.setLayout(myFavouritePanelLayout);
        myFavouritePanelLayout.setHorizontalGroup(
            myFavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFavouritePanelLayout.createSequentialGroup()
                .addGroup(myFavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myFavouritePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(myFavourtiteLabel))
                    .addGroup(myFavouritePanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(symbol1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myFavouritesNumber)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        myFavouritePanelLayout.setVerticalGroup(
            myFavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myFavouritePanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(myFavouritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myFavouritePanelLayout.createSequentialGroup()
                        .addComponent(symbol1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myFavourtiteLabel)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myFavouritePanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myFavouritePanelLayout.createSequentialGroup()
                        .addComponent(myFavouritesNumber)
                        .addGap(38, 38, 38))))
        );

        recipesCookedPanel.setBackground(new java.awt.Color(252, 237, 237));

        recipesCookedLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        recipesCookedLabel.setText("Recipes Cooked");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel15.setText("|");

        recipesCookedNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        recipesCookedNumber.setText("0");

        symbol2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol2.png"))); // NOI18N

        javax.swing.GroupLayout recipesCookedPanelLayout = new javax.swing.GroupLayout(recipesCookedPanel);
        recipesCookedPanel.setLayout(recipesCookedPanelLayout);
        recipesCookedPanelLayout.setHorizontalGroup(
            recipesCookedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipesCookedPanelLayout.createSequentialGroup()
                .addGroup(recipesCookedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recipesCookedPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(recipesCookedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipesCookedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(symbol2)
                        .addGap(30, 30, 30)))
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipesCookedNumber)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        recipesCookedPanelLayout.setVerticalGroup(
            recipesCookedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipesCookedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(recipesCookedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipesCookedPanelLayout.createSequentialGroup()
                        .addComponent(symbol2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recipesCookedLabel)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipesCookedPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipesCookedPanelLayout.createSequentialGroup()
                        .addComponent(recipesCookedNumber)
                        .addGap(40, 40, 40))))
        );

        jPanel12.setBackground(new java.awt.Color(252, 237, 237));

        requestedLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        requestedLabel.setText("Requested");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("|");

        requestedNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        requestedNumber.setText("0");

        symbol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/symbol3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(requestedLabel)
                    .addComponent(symbol3))
                .addGap(28, 28, 28)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestedNumber)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(symbol3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requestedLabel)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(requestedNumber)
                        .addGap(40, 40, 40))))
        );

        recentlyAddedPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        myStatsLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        myStatsLabel1.setForeground(new java.awt.Color(120, 1, 1));
        myStatsLabel1.setText("My Stats");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner.png"))); // NOI18N

        javax.swing.GroupLayout homePanelUserLayout = new javax.swing.GroupLayout(homePanelUser);
        homePanelUser.setLayout(homePanelUserLayout);
        homePanelUserLayout.setHorizontalGroup(
            homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recentlyAddedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homePanelUserLayout.createSequentialGroup()
                        .addComponent(myFavouritePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(recipesCookedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(homePanelUserLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myStatsLabel)
                .addGap(415, 415, 415))
            .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelUserLayout.createSequentialGroup()
                    .addContainerGap(456, Short.MAX_VALUE)
                    .addComponent(myStatsLabel1)
                    .addGap(446, 446, 446)))
        );
        homePanelUserLayout.setVerticalGroup(
            homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelUserLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myFavouritePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipesCookedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(myStatsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recentlyAddedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(homePanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homePanelUserLayout.createSequentialGroup()
                    .addGap(267, 267, 267)
                    .addComponent(myStatsLabel1)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );

        basePanel.add(homePanelUser, "card6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        basePanel.add(jPanel6, "card5");

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        basePanel.add(jPanel4, "card3");

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        basePanel.add(jPanel1, "card2");

        browseRecipesPanel.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout browseRecipesPanelLayout = new javax.swing.GroupLayout(browseRecipesPanel);
        browseRecipesPanel.setLayout(browseRecipesPanelLayout);
        browseRecipesPanelLayout.setHorizontalGroup(
            browseRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseRecipesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addContainerGap())
        );
        browseRecipesPanelLayout.setVerticalGroup(
            browseRecipesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseRecipesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );

        basePanel.add(browseRecipesPanel, "card4");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(navMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        getContentPane().add(userPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JPanel createRecipeCard(AppModel.RecipeData r) {
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setPreferredSize(new java.awt.Dimension(0, 300)); 
        card.setBackground(new java.awt.Color(254, 238, 238));
        card.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(210, 170, 160)));
        card.setLayout(new java.awt.BorderLayout(5, 5));

        // image at top
        javax.swing.JLabel imgLabel = new javax.swing.JLabel();
        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setPreferredSize(new java.awt.Dimension(0, 180)); 

        if (r.imagePath != null) {
            java.net.URL imgUrl = getClass().getResource(r.imagePath);
            if (imgUrl != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
                java.awt.Image scaled = icon.getImage().getScaledInstance(
                        200, 140, java.awt.Image.SCALE_SMOOTH);
                imgLabel.setIcon(new javax.swing.ImageIcon(scaled));
            } else {
                imgLabel.setText("No image");
            }
        } else {
            imgLabel.setText("No image");
        }

        // text center
        javax.swing.JLabel lblTitle = new javax.swing.JLabel(r.title);
        lblTitle.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        javax.swing.JLabel lblMeta = new javax.swing.JLabel(
                r.cuisine + " • " + r.difficulty);
        javax.swing.JLabel lblTimeRating = new javax.swing.JLabel(
                r.prepTime + " min • " + r.rating + " ★");

        javax.swing.JPanel center = new javax.swing.JPanel();
        center.setOpaque(false);
        center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.Y_AXIS));
        center.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
        center.add(lblTitle);
        center.add(lblMeta);
        center.add(lblTimeRating);
        card.add(center, java.awt.BorderLayout.CENTER);

        javax.swing.JButton btnView = new javax.swing.JButton("View");
        btnView.setBackground(new java.awt.Color(0x60, 0x1a, 0x1a));
        btnView.setForeground(java.awt.Color.WHITE);
        btnView.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        btnView.setMargin(new java.awt.Insets(5, 15, 5, 15));
        recentlyAddedPanel.setBackground(java.awt.Color.WHITE);

        card.add(imgLabel, java.awt.BorderLayout.NORTH);
        card.add(center, java.awt.BorderLayout.CENTER);
        card.add(btnView, java.awt.BorderLayout.SOUTH);

        return card;
    }

    
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        handleLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void browseRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseRecipeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_browseRecipeButtonActionPerformed

    private void myHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myHistoryButtonActionPerformed

    private void homeButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonFocusGained

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure you want to log out?","Confirm Logout",javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            CardLayout cl = (CardLayout) getContentPane().getLayout();
            cl.show(getContentPane(), "card3"); 
            usernameField.setText("");
            passwordField.setText("");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppViewFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton browseRecipeButton;
    private javax.swing.JPanel browseRecipesPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanelUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginPageImg;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myFavoriteButton;
    private javax.swing.JPanel myFavouritePanel;
    private javax.swing.JLabel myFavouritesNumber;
    private javax.swing.JLabel myFavourtiteLabel;
    private javax.swing.JButton myHistoryButton;
    private javax.swing.JButton myRecipeRequestButton;
    private javax.swing.JLabel myStatsLabel;
    private javax.swing.JLabel myStatsLabel1;
    private javax.swing.JPanel navMainPanel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel recentlyAddedPanel;
    private javax.swing.JLabel recipesCookedLabel;
    private javax.swing.JLabel recipesCookedNumber;
    private javax.swing.JPanel recipesCookedPanel;
    private javax.swing.JLabel requestedLabel;
    private javax.swing.JLabel requestedNumber;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JLabel symbol1;
    private javax.swing.JLabel symbol2;
    private javax.swing.JLabel symbol3;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topNavPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
